name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compile
        run: mvn clean compile

      - name: Run unit test
        run: mvn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/

      - name: generate coverage report
        run: mvn verify

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Package Application 
        run: mvn package

      - name: Build Docker Image
        run: |
          docker build -t java-test:${{ github.sha }} .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: java-test:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
